name: 'update'
on:
  schedule:
    - cron: 0 0,4,8,12,12,16,20 * * *
jobs:
  runscript:
    runs-on: ubuntu-latest
    steps:
      - name: 'checkout'
        uses: actions/checkout@v4
      - name: 'update'
        run: cd scripts && yarn add axios && node ./autoUpdate.js
      - name: 'show packs'
        run: cat packages.json
